dw_ang_delta: 3
dw_ang_moffs: 1
dw_ang_poffs: 2
dw_ang_factor: 100.0
dw_ang_step: 1

dw_lin_delta: 4
dw_lin_moffs: 0
dw_lin_poffs: 3
dw_lin_factor: 100.0
dw_lin_step: 1

dw_stop_bttn: 9

fw_ang_delta: 0
fw_ang_moffs: 5
fw_ang_poffs: 4
fw_ang_factor: 100.0
fw_ang_step: 1

fw_lin_delta: 1
fw_lin_moffs: 10
fw_lin_poffs: 6
fw_lin_factor: 100.0
fw_lin_step: 1

fw_stop_bttn: 8

pause_bttn: 7

