auto_brightness: 1
auto_exposure: 1
auto_focus: 1
auto_frame_rate_feature: 3
auto_gain: 1
auto_gamma: 1
auto_hue: 1
auto_iris: 1
auto_pan: 1
auto_saturation: 1
auto_sharpness: 1
auto_shutter: 1
auto_white_balance: 1
auto_zoom: 1

bayer_method: ''
bayer_pattern: grbg
binning_x: 0
binning_y: 0
brightness: 0.0

camera_info_url_left: 'package://fugu_configurations/camera_comp_wide/calibration_left.yaml'
camera_info_url_right: 'package://fugu_configurations/camera_comp_wide/calibration_right.yaml'

exposure: 0.0

focus: 0.0
format7_color_coding: raw16
format7_packet_size: 2048
frame_rate: 15.0
frame_rate_feature: 1232.0

gain: 0.0
gamma: 2.2000000000000002
guid: '00b09d0100a8a2c7'

hue: 0.0

iris: 8.0
iso_speed: 400

pan: 0.0

reset_on_open: false
roi_height: 0
roi_width: 0

saturation: 1.0
sharpness: 1.0
shutter: 1.0

stereo_method: Interlaced

video_mode: format7_mode3

white_balance_BU: 0.0
white_balance_RV: 0.0

x_offset: 0

y_offset: 0

zoom: 0.0
